import { Service } from './interfaces/service.interface';

export const SERVICES: Service[] = [
  {
    id: '1',
    name: "Marta's Appliance Repair",
    category: 'repairs',
    neighbourhood: 'Södermalm',
    rating: 4.9,
    reviewCount: 84,
    available: true,
    tags: ['Same-day', 'Certified', 'Washing machines'],
    price: 45,
    priceUnit: 'per hour',
  },
  {
    id: '2',
    name: "Paulo's Guitar Lessons",
    category: 'tutoring',
    neighbourhood: 'Östermalm',
    rating: 5,
    reviewCount: 41,
    available: true,
    tags: ['Beginners welcome', 'Classical & Rock', 'Online available'],
    price: 35,
    priceUnit: 'per hour',
  },
  {
    id: '3',
    name: 'Green Thumb Garden Co.',
    category: 'garden',
    neighbourhood: 'Vasastan',
    rating: 4.8,
    reviewCount: 127,
    available: true,
    tags: ['Balconies', 'Full gardens', 'Seasonal planting'],
    price: 55,
    priceUnit: 'per hour',
  },
  {
    id: '4',
    name: "Lena's Home Bakes",
    category: 'food',
    neighbourhood: 'Kungsholmen',
    rating: 4.7,
    reviewCount: 63,
    available: false,
    tags: ['Custom cakes', 'Vegan options'],
    price: 30,
    priceUnit: 'per hour',
  },
  {
    id: '5',
    name: "Sofia's Nail Studio",
    category: 'beauty',
    neighbourhood: 'Gamla Stan',
    rating: 4.9,
    reviewCount: 152,
    available: true,
    tags: ['Gel', 'Manicure', 'Walk-ins'],
    price: 28,
    priceUnit: 'per session',
  },
  {
    id: '6',
    name: 'Sparkle Clean Stockholm',
    category: 'cleaning',
    neighbourhood: 'Norrmalm',
    rating: 4.6,
    reviewCount: 98,
    available: true,
    tags: ['Deep clean', 'Eco products', 'Insured'],
    price: 22,
    priceUnit: 'per hour',
  },
  {
    id: '7',
    name: "Dev's Photo Studio",
    category: 'photography',
    neighbourhood: 'Djurgården',
    rating: 4.9,
    reviewCount: 76,
    available: false,
    tags: ['Portraits', 'Events', 'Studio & outdoor'],
    price: 90,
    priceUnit: 'per hour',
  },
  {
    id: '8',
    name: 'Happy Paws Pet Sitting',
    category: 'pet_care',
    neighbourhood: 'Hägersten',
    rating: 5,
    reviewCount: 39,
    available: true,
    tags: ['Dog walking', 'Overnight stays'],
    price: 18,
    priceUnit: 'per hour',
  },
];
